package foas

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ModifyMainSpec invokes the foas.ModifyMainSpec API synchronously
// api document: https://help.aliyun.com/api/foas/modifymasterspec.html
func (client *Client) ModifyMainSpec(request *ModifyMainSpecRequest) (response *ModifyMainSpecResponse, err error) {
	response = CreateModifyMainSpecResponse()
	err = client.DoAction(request, response)
	return
}

// ModifyMainSpecWithChan invokes the foas.ModifyMainSpec API asynchronously
// api document: https://help.aliyun.com/api/foas/modifymasterspec.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ModifyMainSpecWithChan(request *ModifyMainSpecRequest) (<-chan *ModifyMainSpecResponse, <-chan error) {
	responseChan := make(chan *ModifyMainSpecResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.ModifyMainSpec(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// ModifyMainSpecWithCallback invokes the foas.ModifyMainSpec API asynchronously
// api document: https://help.aliyun.com/api/foas/modifymasterspec.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ModifyMainSpecWithCallback(request *ModifyMainSpecRequest, callback func(response *ModifyMainSpecResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *ModifyMainSpecResponse
		var err error
		defer close(result)
		response, err = client.ModifyMainSpec(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// ModifyMainSpecRequest is the request struct for api ModifyMainSpec
type ModifyMainSpecRequest struct {
	*requests.RoaRequest
	ClusterId         string `position:"Path" name:"clusterId"`
	MainTargetModel string `position:"Body" name:"mainTargetModel"`
}

// ModifyMainSpecResponse is the response struct for api ModifyMainSpec
type ModifyMainSpecResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateModifyMainSpecRequest creates a request to invoke ModifyMainSpec API
func CreateModifyMainSpecRequest() (request *ModifyMainSpecRequest) {
	request = &ModifyMainSpecRequest{
		RoaRequest: &requests.RoaRequest{},
	}
	request.InitWithApiInfo("foas", "2018-11-11", "ModifyMainSpec", "/api/v2/clusters/[clusterId]/specification", "foas", "openAPI")
	request.Method = requests.PUT
	return
}

// CreateModifyMainSpecResponse creates a response to parse from ModifyMainSpec response
func CreateModifyMainSpecResponse() (response *ModifyMainSpecResponse) {
	response = &ModifyMainSpecResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
