package slb

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DeleteMainSubordinateServerGroup invokes the slb.DeleteMainSubordinateServerGroup API synchronously
// api document: https://help.aliyun.com/api/slb/deletemasterslaveservergroup.html
func (client *Client) DeleteMainSubordinateServerGroup(request *DeleteMainSubordinateServerGroupRequest) (response *DeleteMainSubordinateServerGroupResponse, err error) {
	response = CreateDeleteMainSubordinateServerGroupResponse()
	err = client.DoAction(request, response)
	return
}

// DeleteMainSubordinateServerGroupWithChan invokes the slb.DeleteMainSubordinateServerGroup API asynchronously
// api document: https://help.aliyun.com/api/slb/deletemasterslaveservergroup.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DeleteMainSubordinateServerGroupWithChan(request *DeleteMainSubordinateServerGroupRequest) (<-chan *DeleteMainSubordinateServerGroupResponse, <-chan error) {
	responseChan := make(chan *DeleteMainSubordinateServerGroupResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.DeleteMainSubordinateServerGroup(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// DeleteMainSubordinateServerGroupWithCallback invokes the slb.DeleteMainSubordinateServerGroup API asynchronously
// api document: https://help.aliyun.com/api/slb/deletemasterslaveservergroup.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DeleteMainSubordinateServerGroupWithCallback(request *DeleteMainSubordinateServerGroupRequest, callback func(response *DeleteMainSubordinateServerGroupResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *DeleteMainSubordinateServerGroupResponse
		var err error
		defer close(result)
		response, err = client.DeleteMainSubordinateServerGroup(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// DeleteMainSubordinateServerGroupRequest is the request struct for api DeleteMainSubordinateServerGroup
type DeleteMainSubordinateServerGroupRequest struct {
	*requests.RpcRequest
	AccessKeyId              string           `position:"Query" name:"access_key_id"`
	ResourceOwnerId          requests.Integer `position:"Query" name:"ResourceOwnerId"`
	ResourceOwnerAccount     string           `position:"Query" name:"ResourceOwnerAccount"`
	OwnerAccount             string           `position:"Query" name:"OwnerAccount"`
	OwnerId                  requests.Integer `position:"Query" name:"OwnerId"`
	Tags                     string           `position:"Query" name:"Tags"`
	MainSubordinateServerGroupId string           `position:"Query" name:"MainSubordinateServerGroupId"`
}

// DeleteMainSubordinateServerGroupResponse is the response struct for api DeleteMainSubordinateServerGroup
type DeleteMainSubordinateServerGroupResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateDeleteMainSubordinateServerGroupRequest creates a request to invoke DeleteMainSubordinateServerGroup API
func CreateDeleteMainSubordinateServerGroupRequest() (request *DeleteMainSubordinateServerGroupRequest) {
	request = &DeleteMainSubordinateServerGroupRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Slb", "2014-05-15", "DeleteMainSubordinateServerGroup", "slb", "openAPI")
	return
}

// CreateDeleteMainSubordinateServerGroupResponse creates a response to parse from DeleteMainSubordinateServerGroup response
func CreateDeleteMainSubordinateServerGroupResponse() (response *DeleteMainSubordinateServerGroupResponse) {
	response = &DeleteMainSubordinateServerGroupResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
